# This is a config for E2B sandbox template.
# You can use template ID (xbtfo6kjkxdeycn95ll7) or template name (vibe-nextjs-test62) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test62") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test62") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test62')

team_id = "a05ac1ef-f0c4-4182-97d3-654cf40a6b43"
start_cmd = "compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test62"
template_id = "xbtfo6kjkxdeycn95ll7"
